/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 27 08:01:09 GMT 2017
 */

package org.cs362.dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import org.cs362.dominion.Card;
import org.cs362.dominion.Deck;
import org.cs362.dominion.Hand;
import org.cs362.dominion.Player;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.TooManyResourcesException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Deck_ESTest extends Deck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Player player0 = new Player("", true);
      Deck deck0 = player0.deck;
      deck0.embargoCounter = 3;
      deck0.addTop((Card) null);
      deck0.deck.add((Card) null);
      // Undeclared exception!
      try { 
        deck0.shuffle();
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Deck deck0 = new Deck();
      deck0.deck.add((Card) null);
      deck0.addBottom((Card) null);
      deck0.deck.add((Card) null);
      // Undeclared exception!
      try { 
        deck0.shuffle();
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Deck deck0 = new Deck();
      deck0.addBottom((Card) null);
      deck0.removeTop();
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Deck deck0 = new Deck();
      deck0.deck.add((Card) null);
      deck0.removeBottom();
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Player player0 = new Player("c?/4FR//?l", false);
      Card card0 = player0.playCard();
      player0.discard.addTop(card0);
      int int0 = player0.discard.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Player player0 = new Player("", true);
      player0.deck.addTop((Card) null);
      Card card0 = player0.deck.getTop();
      assertNull(card0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Player player0 = new Player("5~G;e}!;+d-GZ;", true);
      Deck deck0 = player0.discard;
      Card card0 = player0.playCard();
      deck0.addBottom(card0);
      Card card1 = player0.discard.getTop();
      assertEquals(0, card1.getTreasure());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Player player0 = new Player("", true);
      player0.deck.addTop((Card) null);
      Card card0 = player0.deck.getSpecific((Card) null);
      assertNull(card0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Deck deck0 = new Deck();
      Player player0 = new Player("`y~{Q!NybRdBOQ./C(a", false);
      Card card0 = player0.playCard();
      deck0.deck.add(card0);
      deck0.getSpecific(card0);
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Deck deck0 = new Deck("");
      deck0.getName();
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Player player0 = new Player("", true);
      Deck deck0 = player0.deck;
      deck0.embargoCounter = 1658;
      int int0 = deck0.getEmbargos();
      assertEquals(1658, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Deck deck0 = new Deck();
      deck0.addEmbargos((-1350));
      int int0 = deck0.getEmbargos();
      assertEquals((-1350), int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Deck deck0 = new Deck();
      deck0.deck.add((Card) null);
      deck0.getBottom();
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Deck deck0 = new Deck();
      Player player0 = new Player("`y~{Q!NybRdBOQ./C(a", false);
      Card card0 = player0.playCard();
      deck0.deck.add(card0);
      deck0.getBottom();
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Player player0 = new Player("5~G;e}!;+d-GZ;", false);
      Deck deck0 = player0.deck;
      deck0.addBottom((Card) null);
      deck0.findSpecific((Card) null);
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Player player0 = new Player("5~G;e}!;+d-GZ;", true);
      Deck deck0 = player0.discard;
      Card card0 = player0.playCard();
      deck0.addBottom(card0);
      Card card1 = player0.discard.findSpecific(card0);
      assertEquals(0, card1.getTreasure());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Player player0 = new Player("", true);
      player0.discard.addTop((Card) null);
      Card card0 = player0.discard.findSpecific(0);
      assertNull(card0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Deck deck0 = new Deck();
      deck0.deck.add((Card) null);
      deck0.drawTop();
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Player player0 = new Player("5~G;e}!;+d-GZ;", false);
      Deck deck0 = player0.deck;
      Card card0 = player0.playCard();
      deck0.addBottom(card0);
      deck0.drawTop();
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Player player0 = new Player("", true);
      Deck deck0 = player0.deck;
      Deck deck1 = new Deck();
      ArrayList<Card> arrayList0 = deck1.deck;
      deck0.deck = arrayList0;
      deck0.addTop((Card) null);
      assertEquals(0, deck0.getEmbargos());
      
      deck1.drawBottom();
      assertEquals(0, deck1.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Player player0 = new Player("", false);
      Deck deck0 = player0.discard;
      deck0.deck = null;
      // Undeclared exception!
      try { 
        deck0.size();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.Deck", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Deck deck0 = new Deck("");
      deck0.deck = null;
      // Undeclared exception!
      try { 
        deck0.removeTop();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.Deck", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Deck deck0 = new Deck();
      deck0.deck = null;
      // Undeclared exception!
      try { 
        deck0.isCard((Card) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.Deck", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Deck deck0 = new Deck();
      // Undeclared exception!
      try { 
        deck0.findSpecific((-1119));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Deck deck0 = new Deck();
      Hand hand0 = new Hand();
      deck0.deck = hand0.hand;
      deck0.deck = null;
      // Undeclared exception!
      try { 
        deck0.drawTop();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.Deck", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Deck deck0 = new Deck("");
      deck0.deck = null;
      // Undeclared exception!
      try { 
        deck0.drawBottom();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.Deck", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Player player0 = new Player("5~G;e}!;+d-GZ;", false);
      Deck deck0 = player0.discard;
      deck0.deck = null;
      Card card0 = player0.playCard();
      // Undeclared exception!
      try { 
        deck0.addBottom(card0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.Deck", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Deck deck0 = new Deck("");
      // Undeclared exception!
      try { 
        deck0.removeTop();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Deck deck0 = new Deck((String) null);
      deck0.getName();
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Deck deck0 = new Deck();
      // Undeclared exception!
      try { 
        deck0.getBottom();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         assertThrownBy("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Player player0 = new Player("", true);
      Card card0 = player0.playCard();
      boolean boolean0 = player0.discard.isCard(card0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Player player0 = new Player("", true);
      player0.deck.shuffle();
      assertEquals(0, player0.numCardsDeck());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Player player0 = new Player("", true);
      // Undeclared exception!
      try { 
        player0.deck.findSpecific(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         assertThrownBy("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Deck deck0 = new Deck();
      Player player0 = new Player("`y~{Q!NybRdBOQ./C(a", false);
      Card card0 = player0.playCard();
      deck0.deck.add(card0);
      deck0.drawBottom();
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Player player0 = new Player("", true);
      int int0 = player0.deck.getEmbargos();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Player player0 = new Player("", true);
      player0.deck.setName("q=@1wv[%");
      assertEquals(0, player0.getBuys());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Deck deck0 = new Deck();
      // Undeclared exception!
      try { 
        deck0.removeBottom();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         assertThrownBy("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Player player0 = new Player("", true);
      int int0 = player0.deck.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Deck deck0 = new Deck();
      // Undeclared exception!
      try { 
        deck0.drawBottom();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         assertThrownBy("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Player player0 = new Player("", true);
      Card card0 = player0.playCard();
      player0.discard.addBottom(card0);
      Card card1 = player0.discard.findSpecific(0);
      assertEquals("", card1.getName());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Player player0 = new Player("", true);
      String string0 = player0.discard.getName();
      assertEquals("Discard", string0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Player player0 = new Player("", true);
      // Undeclared exception!
      try { 
        player0.deck.getSpecific((Card) null);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Deck deck0 = new Deck();
      // Undeclared exception!
      try { 
        deck0.drawTop();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Player player0 = new Player("", true);
      player0.deck.addTop((Card) null);
      boolean boolean0 = player0.deck.isCard((Card) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Player player0 = new Player("", true);
      // Undeclared exception!
      try { 
        player0.deck.getTop();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Deck deck0 = new Deck();
      deck0.removeSpecific((Card) null);
      assertEquals(0, deck0.getEmbargos());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Player player0 = new Player("5~G;e}!;+d-GZ;", true);
      Card card0 = player0.playCard();
      // Undeclared exception!
      try { 
        player0.discard.findSpecific(card0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
