compile:
	javac Card.java
	javac GameState.java
	javac Player.java
	javac PlayDominion.java
	javac RandomTestDominion.java
	
play2:
	java PlayDominion
	
play24:
	java RandomTestDominion

clean:
	rm -f *.class
