/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 27 16:32:15 GMT 2017
 */

package org.cs362.dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.cs362.dominion.Cutpurse;
import org.cs362.dominion.GameState;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Cutpurse_ESTest extends Cutpurse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Cutpurse cutpurse0 = new Cutpurse();
      GameState gameState0 = new GameState(4, (-3502));
      gameState0.numPlayers = (-3502);
      cutpurse0.play(gameState0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Cutpurse cutpurse0 = new Cutpurse();
      GameState gameState0 = new GameState(3, 3);
      gameState0.phase = 3;
      cutpurse0.play(gameState0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Cutpurse cutpurse0 = new Cutpurse();
      // Undeclared exception!
      try { 
        cutpurse0.play((GameState) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.Cutpurse", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Cutpurse cutpurse0 = new Cutpurse();
      GameState gameState0 = new GameState(2, 840);
      gameState0.numPlayers = 4525;
      // Undeclared exception!
      try { 
        cutpurse0.play(gameState0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         assertThrownBy("org.cs362.dominion.Cutpurse", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Cutpurse cutpurse0 = new Cutpurse();
      GameState gameState0 = new GameState(2, 2);
      gameState0.phase = (-3077);
      Boolean boolean0 = cutpurse0.play(gameState0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Cutpurse cutpurse0 = new Cutpurse();
      GameState gameState0 = new GameState(2, 2);
      cutpurse0.play(gameState0);
      cutpurse0.play(gameState0);
      cutpurse0.play(gameState0);
      Boolean boolean0 = cutpurse0.play(gameState0);
      assertTrue(boolean0);
  }
}
