/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 27 22:40:45 GMT 2017
 */

package dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dominion.PlayGame;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.TooManyResourcesException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PlayGame_ESTest extends PlayGame_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = ">s:!6";
      PlayGame playGame0 = new PlayGame();
      // Undeclared exception!
      try { 
        playGame0.jeu(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PlayGame playGame0 = new PlayGame();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "-2";
      int int0 = playGame0.jeu(stringArray0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[4];
      stringArray0[0] = "-1";
      PlayGame playGame0 = new PlayGame();
      int int0 = playGame0.jeu(stringArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlayGame playGame0 = new PlayGame();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "-3";
      int int0 = playGame0.jeu(stringArray0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[4];
      PlayGame playGame0 = new PlayGame();
      // Undeclared exception!
      try { 
        playGame0.jeu(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlayGame playGame0 = new PlayGame();
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        playGame0.jeu(stringArray0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }
}
