/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 13 07:56:04 GMT 2017
 */

package dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import dominion.Treasure;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Treasure_ESTest extends Treasure_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 5 covered goals:
   * Goal 1. dominion.Treasure.<init>(I)V: root-Branch
   * Goal 2. Branch dominion.Treasure.<init>(I)V: root-Branch in context: dominion.Treasure:<init>(I)V
   * Goal 3. dominion.Treasure.<init>(I)V: Line 8
   * Goal 4. [METHOD] dominion.Treasure.<init>(I)V
   * Goal 5. [METHODNOEX] dominion.Treasure.<init>(I)V
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Treasure treasure0 = new Treasure((-1411));
  }
}
