/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 28 04:04:04 GMT 2017
 */

package org.thenellb;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.thenellb.Province;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Province_ESTest extends Province_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Province province0 = new Province();
      int int0 = province0.activate();
      assertEquals(0, province0.get_plusTreasuryValue());
      assertEquals(8, province0.get_cost());
      assertEquals(0, province0.get_plusCardValue());
      assertEquals(20, int0);
      assertEquals("VICTORY", province0.get_cardType());
      assertEquals(0, province0.get_plusActionValue());
      assertEquals(6, province0.get_victoryValue());
      assertEquals(0, province0.get_plusBuyValue());
      assertEquals("Province", province0.get_cardName());
  }
}
