/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 22 23:52:44 GMT 2017
 */

package org.cs362.dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.cs362.dominion.Card;
import org.cs362.dominion.Game;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Game_ESTest extends Game_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Card[] cardArray0 = new Card[9];
      Card card0 = Card.GREAT_HALL;
      cardArray0[0] = card0;
      cardArray0[1] = card0;
      cardArray0[2] = card0;
      cardArray0[3] = card0;
      cardArray0[4] = card0;
      cardArray0[5] = card0;
      cardArray0[6] = cardArray0[3];
      cardArray0[7] = card0;
      cardArray0[8] = card0;
      Game game0 = null;
      try {
        game0 = new Game(cardArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 9
         //
         assertThrownBy("org.cs362.dominion.Game", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Card[] cardArray0 = new Card[9];
      Card card0 = Card.GREAT_HALL;
      cardArray0[0] = card0;
      cardArray0[1] = card0;
      cardArray0[2] = card0;
      cardArray0[3] = card0;
      cardArray0[4] = card0;
      cardArray0[5] = card0;
      Card card1 = Card.SILVER;
      cardArray0[6] = card1;
      Game game0 = null;
      try {
        game0 = new Game(cardArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.Game", e);
      }
  }
}
