/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 28 04:04:43 GMT 2017
 */

package org.thenellb;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.thenellb.Duchy;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Duchy_ESTest extends Duchy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Duchy duchy0 = new Duchy();
      int int0 = duchy0.activate();
      assertEquals(0, duchy0.get_plusBuyValue());
      assertEquals("VICTORY", duchy0.get_cardType());
      assertEquals(3, duchy0.get_victoryValue());
      assertEquals(0, duchy0.get_plusActionValue());
      assertEquals(5, duchy0.get_cost());
      assertEquals(0, duchy0.get_plusCardValue());
      assertEquals(18, int0);
      assertEquals("Duchy", duchy0.get_cardName());
      assertEquals(0, duchy0.get_plusTreasuryValue());
  }
}
