/*
 * This file was automatically generated by EvoSuite
 * Mon Feb 27 08:09:37 GMT 2017
 */

package org.cs362.dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import org.cs362.dominion.Adventurer;
import org.cs362.dominion.Board;
import org.cs362.dominion.Player;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.TooManyResourcesException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class Adventurer_ESTest extends Adventurer_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Adventurer adventurer0 = new Adventurer();
      ArrayList<Player> arrayList0 = new ArrayList<Player>();
      Player player0 = new Player((String) null, false);
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        adventurer0.Action(arrayList0, player0, board0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Adventurer adventurer0 = new Adventurer();
      ArrayList<Player> arrayList0 = new ArrayList<Player>();
      Player player0 = new Player("org.apache.xerces.jaxp.datatype.XMLGregorianCalendarImpl", true);
      player0.giveCard(adventurer0);
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        adventurer0.Action(arrayList0, player0, board0);
        fail("Expecting exception: TooManyResourcesException");
      
      } catch(TooManyResourcesException e) {
         //
         // Loop has been executed more times than the allowed 10000
         //
         assertThrownBy("org.evosuite.runtime.LoopCounter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Adventurer adventurer0 = new Adventurer();
      ArrayList<Player> arrayList0 = new ArrayList<Player>();
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        adventurer0.Action(arrayList0, (Player) null, board0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.cs362.dominion.Adventurer", e);
      }
  }
}
