/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 28 23:39:19 GMT 2017
 */

package com.mycompany.marksprousedominion;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mycompany.marksprousedominion.treasureCard;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class treasureCard_ESTest extends treasureCard_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      treasureCard treasureCard0 = new treasureCard(2122, 0, "LkF2xLL8QeN+2v");
      assertEquals(0, treasureCard0.getVictory());
      assertEquals(2122, treasureCard0.getCost());
      assertEquals(1, treasureCard0.getType());
      assertEquals(0, treasureCard0.getTreasure());
  }
}
